---

- name: Ensure ~/.gitconfig copied from ../files/master.gitconfig
  hosts: localhost
  tasks:
    - name: Copy master.gitconfig to ~/.gitconfig
      copy: 
        src: "../files/master.gitconfig"
        dest: "~/.gitconfig"

- name: Ensure packages are installed
  hosts: localhost
  tasks:
  - apt:
      name: jq
      state: latest