---

- name: Ensure git installed
  hosts: all
  tasks:
  - package: name=git state=latest
    become: yes


- name: Ensure ~/.gitconfig copied from ../files/master.gitconfig
  hosts: all
  tasks:
    - name: Copy master.gitconfig to ~/.gitconfig
      copy: 
        src: "../files/master.gitconfig"
        dest: "~/.gitconfig"

